#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

c=1

while [ $c -le 10 ]
do
    if [ $c -eq 9 ]
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi

    ((c++))
done

